### ISSUE TITLE
access please.

### ISSUE THREAD

**Issue by asaikali** [FlorianRappl/qconsf-mf-workshop#1]

**Comment by Ruthenz** [comment]
Would like access too please :)

**Comment by nathan-ferrel** [comment]
Me as well

**Comment by tsprouls** [comment]
Me as well, thanks!

**Comment by yaihui** [comment]
Me as well, thanks!

**Comment by BenLeech** [comment]
I would also like access please, thank you.

**Comment by zheyong91** [comment]
Me too thanks!!!

**Comment by zahersbg** [comment]
me too please

**Comment by Jesus-Elizalde** [comment]
i would also like access please, thank you

**Comment by ruud** [comment]
Can you add me too?
Thanks in advance

**Comment by RebootJeff** [comment]
Please add me as well 🙏

**Comment by edmundask** [comment]
please add me too, thanks
